name: CI/CD Pipeline

on:
  push:
    branches:
        estimation-github-alar12-240131

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.11
        ports:
          - "8080:80"
        environment:
          - NODE_ENV=production

    steps:
      - name: Checkout Repository

      - name: Build and Test React App
        run: |
          cd react-app
          npm install
          npm test

      - name: Build and Test Node.js App
        run: |
          cd node-app
          npm install
          npm test

      - name: Build Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest ./react-app
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest ./node-app

      - name: Push Docker Images to Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

     
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy