version: "3"
services:
  app:
    image: psd
    ports:
      - "8080:80"
    volumes:
      - ./crew_manual:/crew_manual
    environment:
      - NODE_ENV=development
  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_DB=your_database
  #     - POSTGRES_USER=your_user
  #     - POSTGRES_PASSWORD=your_password